version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 376129879284.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t ai2 .
      - docker tag ai2:latest 376129879284.dkr.ecr.ap-south-1.amazonaws.com/ai2:latest
  post_build:
    commands:
      - docker push 376129879284.dkr.ecr.ap-south-1.amazonaws.com/ai2:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ai2","imageUri":"%s"}]' 376129879284.dkr.ecr.us-east-1.amazonaws.com/ai2:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
